// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.estudo.Data;

#nullable disable

namespace api.estudo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.estudo.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokedexNumber")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
                            Name = "bulbasaur",
                            PokedexNumber = 1,
                            Type = "grass",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png",
                            Name = "ivysaur",
                            PokedexNumber = 2,
                            Type = "grass",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 3,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",
                            Name = "venusaur",
                            PokedexNumber = 3,
                            Type = "grass",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 4,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
                            Name = "charmander",
                            PokedexNumber = 4,
                            Type = "fire",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 5,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png",
                            Name = "charmeleon",
                            PokedexNumber = 5,
                            Type = "fire",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 6,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
                            Name = "charizard",
                            PokedexNumber = 6,
                            Type = "fire",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 7,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
                            Name = "squirtle",
                            PokedexNumber = 7,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 8,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png",
                            Name = "wartortle",
                            PokedexNumber = 8,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 9,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",
                            Name = "blastoise",
                            PokedexNumber = 9,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 10,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",
                            Name = "caterpie",
                            PokedexNumber = 10,
                            Type = "bug",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 11,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png",
                            Name = "metapod",
                            PokedexNumber = 11,
                            Type = "bug",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 12,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png",
                            Name = "butterfree",
                            PokedexNumber = 12,
                            Type = "bug",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 13,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png",
                            Name = "weedle",
                            PokedexNumber = 13,
                            Type = "bug",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 14,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png",
                            Name = "kakuna",
                            PokedexNumber = 14,
                            Type = "bug",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 15,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png",
                            Name = "beedrill",
                            PokedexNumber = 15,
                            Type = "bug",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 16,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",
                            Name = "pidgey",
                            PokedexNumber = 16,
                            Type = "normal",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 17,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png",
                            Name = "pidgeotto",
                            PokedexNumber = 17,
                            Type = "normal",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 18,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png",
                            Name = "pidgeot",
                            PokedexNumber = 18,
                            Type = "normal",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 19,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png",
                            Name = "rattata",
                            PokedexNumber = 19,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 20,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png",
                            Name = "raticate",
                            PokedexNumber = 20,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 21,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png",
                            Name = "spearow",
                            PokedexNumber = 21,
                            Type = "normal",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 22,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png",
                            Name = "fearow",
                            PokedexNumber = 22,
                            Type = "normal",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 23,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png",
                            Name = "ekans",
                            PokedexNumber = 23,
                            Type = "poison",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 24,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png",
                            Name = "arbok",
                            PokedexNumber = 24,
                            Type = "poison",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 25,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
                            Name = "pikachu",
                            PokedexNumber = 25,
                            Type = "electric",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 26,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png",
                            Name = "raichu",
                            PokedexNumber = 26,
                            Type = "electric",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 27,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png",
                            Name = "sandshrew",
                            PokedexNumber = 27,
                            Type = "ground",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 28,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png",
                            Name = "sandslash",
                            PokedexNumber = 28,
                            Type = "ground",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 29,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png",
                            Name = "nidoran-f",
                            PokedexNumber = 29,
                            Type = "poison",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 30,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png",
                            Name = "nidorina",
                            PokedexNumber = 30,
                            Type = "poison",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 31,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png",
                            Name = "nidoqueen",
                            PokedexNumber = 31,
                            Type = "poison",
                            Type2 = "ground"
                        },
                        new
                        {
                            Id = 32,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png",
                            Name = "nidoran-m",
                            PokedexNumber = 32,
                            Type = "poison",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 33,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png",
                            Name = "nidorino",
                            PokedexNumber = 33,
                            Type = "poison",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 34,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png",
                            Name = "nidoking",
                            PokedexNumber = 34,
                            Type = "poison",
                            Type2 = "ground"
                        },
                        new
                        {
                            Id = 35,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png",
                            Name = "clefairy",
                            PokedexNumber = 35,
                            Type = "fairy",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 36,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png",
                            Name = "clefable",
                            PokedexNumber = 36,
                            Type = "fairy",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 37,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png",
                            Name = "vulpix",
                            PokedexNumber = 37,
                            Type = "fire",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 38,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png",
                            Name = "ninetales",
                            PokedexNumber = 38,
                            Type = "fire",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 39,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png",
                            Name = "jigglypuff",
                            PokedexNumber = 39,
                            Type = "normal",
                            Type2 = "fairy"
                        },
                        new
                        {
                            Id = 40,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png",
                            Name = "wigglytuff",
                            PokedexNumber = 40,
                            Type = "normal",
                            Type2 = "fairy"
                        },
                        new
                        {
                            Id = 41,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png",
                            Name = "zubat",
                            PokedexNumber = 41,
                            Type = "poison",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 42,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png",
                            Name = "golbat",
                            PokedexNumber = 42,
                            Type = "poison",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 43,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png",
                            Name = "oddish",
                            PokedexNumber = 43,
                            Type = "grass",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 44,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png",
                            Name = "gloom",
                            PokedexNumber = 44,
                            Type = "grass",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 45,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png",
                            Name = "vileplume",
                            PokedexNumber = 45,
                            Type = "grass",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 46,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png",
                            Name = "paras",
                            PokedexNumber = 46,
                            Type = "bug",
                            Type2 = "grass"
                        },
                        new
                        {
                            Id = 47,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png",
                            Name = "parasect",
                            PokedexNumber = 47,
                            Type = "bug",
                            Type2 = "grass"
                        },
                        new
                        {
                            Id = 48,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png",
                            Name = "venonat",
                            PokedexNumber = 48,
                            Type = "bug",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 49,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png",
                            Name = "venomoth",
                            PokedexNumber = 49,
                            Type = "bug",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 50,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png",
                            Name = "diglett",
                            PokedexNumber = 50,
                            Type = "ground",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 51,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png",
                            Name = "dugtrio",
                            PokedexNumber = 51,
                            Type = "ground",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 52,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png",
                            Name = "meowth",
                            PokedexNumber = 52,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 53,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png",
                            Name = "persian",
                            PokedexNumber = 53,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 54,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png",
                            Name = "psyduck",
                            PokedexNumber = 54,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 55,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png",
                            Name = "golduck",
                            PokedexNumber = 55,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 56,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png",
                            Name = "mankey",
                            PokedexNumber = 56,
                            Type = "fighting",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 57,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png",
                            Name = "primeape",
                            PokedexNumber = 57,
                            Type = "fighting",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 58,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png",
                            Name = "growlithe",
                            PokedexNumber = 58,
                            Type = "fire",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 59,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png",
                            Name = "arcanine",
                            PokedexNumber = 59,
                            Type = "fire",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 60,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png",
                            Name = "poliwag",
                            PokedexNumber = 60,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 61,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png",
                            Name = "poliwhirl",
                            PokedexNumber = 61,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 62,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png",
                            Name = "poliwrath",
                            PokedexNumber = 62,
                            Type = "water",
                            Type2 = "fighting"
                        },
                        new
                        {
                            Id = 63,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png",
                            Name = "abra",
                            PokedexNumber = 63,
                            Type = "psychic",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 64,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png",
                            Name = "kadabra",
                            PokedexNumber = 64,
                            Type = "psychic",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 65,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png",
                            Name = "alakazam",
                            PokedexNumber = 65,
                            Type = "psychic",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 66,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png",
                            Name = "machop",
                            PokedexNumber = 66,
                            Type = "fighting",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 67,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png",
                            Name = "machoke",
                            PokedexNumber = 67,
                            Type = "fighting",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 68,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png",
                            Name = "machamp",
                            PokedexNumber = 68,
                            Type = "fighting",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 69,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png",
                            Name = "bellsprout",
                            PokedexNumber = 69,
                            Type = "grass",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 70,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png",
                            Name = "weepinbell",
                            PokedexNumber = 70,
                            Type = "grass",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 71,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png",
                            Name = "victreebel",
                            PokedexNumber = 71,
                            Type = "grass",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 72,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png",
                            Name = "tentacool",
                            PokedexNumber = 72,
                            Type = "water",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 73,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png",
                            Name = "tentacruel",
                            PokedexNumber = 73,
                            Type = "water",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 74,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png",
                            Name = "geodude",
                            PokedexNumber = 74,
                            Type = "rock",
                            Type2 = "ground"
                        },
                        new
                        {
                            Id = 75,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png",
                            Name = "graveler",
                            PokedexNumber = 75,
                            Type = "rock",
                            Type2 = "ground"
                        },
                        new
                        {
                            Id = 76,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png",
                            Name = "golem",
                            PokedexNumber = 76,
                            Type = "rock",
                            Type2 = "ground"
                        },
                        new
                        {
                            Id = 77,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png",
                            Name = "ponyta",
                            PokedexNumber = 77,
                            Type = "fire",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 78,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png",
                            Name = "rapidash",
                            PokedexNumber = 78,
                            Type = "fire",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 79,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png",
                            Name = "slowpoke",
                            PokedexNumber = 79,
                            Type = "water",
                            Type2 = "psychic"
                        },
                        new
                        {
                            Id = 80,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png",
                            Name = "slowbro",
                            PokedexNumber = 80,
                            Type = "water",
                            Type2 = "psychic"
                        },
                        new
                        {
                            Id = 81,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png",
                            Name = "magnemite",
                            PokedexNumber = 81,
                            Type = "electric",
                            Type2 = "steel"
                        },
                        new
                        {
                            Id = 82,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png",
                            Name = "magneton",
                            PokedexNumber = 82,
                            Type = "electric",
                            Type2 = "steel"
                        },
                        new
                        {
                            Id = 83,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png",
                            Name = "farfetchd",
                            PokedexNumber = 83,
                            Type = "normal",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 84,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png",
                            Name = "doduo",
                            PokedexNumber = 84,
                            Type = "normal",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 85,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png",
                            Name = "dodrio",
                            PokedexNumber = 85,
                            Type = "normal",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 86,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png",
                            Name = "seel",
                            PokedexNumber = 86,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 87,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png",
                            Name = "dewgong",
                            PokedexNumber = 87,
                            Type = "water",
                            Type2 = "ice"
                        },
                        new
                        {
                            Id = 88,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png",
                            Name = "grimer",
                            PokedexNumber = 88,
                            Type = "poison",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 89,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png",
                            Name = "muk",
                            PokedexNumber = 89,
                            Type = "poison",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 90,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png",
                            Name = "shellder",
                            PokedexNumber = 90,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 91,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png",
                            Name = "cloyster",
                            PokedexNumber = 91,
                            Type = "water",
                            Type2 = "ice"
                        },
                        new
                        {
                            Id = 92,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png",
                            Name = "gastly",
                            PokedexNumber = 92,
                            Type = "ghost",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 93,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png",
                            Name = "haunter",
                            PokedexNumber = 93,
                            Type = "ghost",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 94,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png",
                            Name = "gengar",
                            PokedexNumber = 94,
                            Type = "ghost",
                            Type2 = "poison"
                        },
                        new
                        {
                            Id = 95,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png",
                            Name = "onix",
                            PokedexNumber = 95,
                            Type = "rock",
                            Type2 = "ground"
                        },
                        new
                        {
                            Id = 96,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png",
                            Name = "drowzee",
                            PokedexNumber = 96,
                            Type = "psychic",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 97,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png",
                            Name = "hypno",
                            PokedexNumber = 97,
                            Type = "psychic",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 98,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png",
                            Name = "krabby",
                            PokedexNumber = 98,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 99,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png",
                            Name = "kingler",
                            PokedexNumber = 99,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 100,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png",
                            Name = "voltorb",
                            PokedexNumber = 100,
                            Type = "electric",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 101,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png",
                            Name = "electrode",
                            PokedexNumber = 101,
                            Type = "electric",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 102,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png",
                            Name = "exeggcute",
                            PokedexNumber = 102,
                            Type = "grass",
                            Type2 = "psychic"
                        },
                        new
                        {
                            Id = 103,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png",
                            Name = "exeggutor",
                            PokedexNumber = 103,
                            Type = "grass",
                            Type2 = "psychic"
                        },
                        new
                        {
                            Id = 104,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png",
                            Name = "cubone",
                            PokedexNumber = 104,
                            Type = "ground",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 105,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png",
                            Name = "marowak",
                            PokedexNumber = 105,
                            Type = "ground",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 106,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png",
                            Name = "hitmonlee",
                            PokedexNumber = 106,
                            Type = "fighting",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 107,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png",
                            Name = "hitmonchan",
                            PokedexNumber = 107,
                            Type = "fighting",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 108,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png",
                            Name = "lickitung",
                            PokedexNumber = 108,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 109,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png",
                            Name = "koffing",
                            PokedexNumber = 109,
                            Type = "poison",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 110,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png",
                            Name = "weezing",
                            PokedexNumber = 110,
                            Type = "poison",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 111,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png",
                            Name = "rhyhorn",
                            PokedexNumber = 111,
                            Type = "ground",
                            Type2 = "rock"
                        },
                        new
                        {
                            Id = 112,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png",
                            Name = "rhydon",
                            PokedexNumber = 112,
                            Type = "ground",
                            Type2 = "rock"
                        },
                        new
                        {
                            Id = 113,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png",
                            Name = "chansey",
                            PokedexNumber = 113,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 114,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png",
                            Name = "tangela",
                            PokedexNumber = 114,
                            Type = "grass",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 115,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png",
                            Name = "kangaskhan",
                            PokedexNumber = 115,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 116,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png",
                            Name = "horsea",
                            PokedexNumber = 116,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 117,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png",
                            Name = "seadra",
                            PokedexNumber = 117,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 118,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png",
                            Name = "goldeen",
                            PokedexNumber = 118,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 119,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png",
                            Name = "seaking",
                            PokedexNumber = 119,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 120,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png",
                            Name = "staryu",
                            PokedexNumber = 120,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 121,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png",
                            Name = "starmie",
                            PokedexNumber = 121,
                            Type = "water",
                            Type2 = "psychic"
                        },
                        new
                        {
                            Id = 122,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png",
                            Name = "mr-mime",
                            PokedexNumber = 122,
                            Type = "psychic",
                            Type2 = "fairy"
                        },
                        new
                        {
                            Id = 123,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png",
                            Name = "scyther",
                            PokedexNumber = 123,
                            Type = "bug",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 124,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png",
                            Name = "jynx",
                            PokedexNumber = 124,
                            Type = "ice",
                            Type2 = "psychic"
                        },
                        new
                        {
                            Id = 125,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png",
                            Name = "electabuzz",
                            PokedexNumber = 125,
                            Type = "electric",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 126,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png",
                            Name = "magmar",
                            PokedexNumber = 126,
                            Type = "fire",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 127,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png",
                            Name = "pinsir",
                            PokedexNumber = 127,
                            Type = "bug",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 128,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png",
                            Name = "tauros",
                            PokedexNumber = 128,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 129,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png",
                            Name = "magikarp",
                            PokedexNumber = 129,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 130,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png",
                            Name = "gyarados",
                            PokedexNumber = 130,
                            Type = "water",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 131,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png",
                            Name = "lapras",
                            PokedexNumber = 131,
                            Type = "water",
                            Type2 = "ice"
                        },
                        new
                        {
                            Id = 132,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png",
                            Name = "ditto",
                            PokedexNumber = 132,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 133,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png",
                            Name = "eevee",
                            PokedexNumber = 133,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 134,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png",
                            Name = "vaporeon",
                            PokedexNumber = 134,
                            Type = "water",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 135,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png",
                            Name = "jolteon",
                            PokedexNumber = 135,
                            Type = "electric",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 136,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png",
                            Name = "flareon",
                            PokedexNumber = 136,
                            Type = "fire",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 137,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png",
                            Name = "porygon",
                            PokedexNumber = 137,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 138,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png",
                            Name = "omanyte",
                            PokedexNumber = 138,
                            Type = "rock",
                            Type2 = "water"
                        },
                        new
                        {
                            Id = 139,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png",
                            Name = "omastar",
                            PokedexNumber = 139,
                            Type = "rock",
                            Type2 = "water"
                        },
                        new
                        {
                            Id = 140,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png",
                            Name = "kabuto",
                            PokedexNumber = 140,
                            Type = "rock",
                            Type2 = "water"
                        },
                        new
                        {
                            Id = 141,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png",
                            Name = "kabutops",
                            PokedexNumber = 141,
                            Type = "rock",
                            Type2 = "water"
                        },
                        new
                        {
                            Id = 142,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png",
                            Name = "aerodactyl",
                            PokedexNumber = 142,
                            Type = "rock",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 143,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png",
                            Name = "snorlax",
                            PokedexNumber = 143,
                            Type = "normal",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 144,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png",
                            Name = "articuno",
                            PokedexNumber = 144,
                            Type = "ice",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 145,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png",
                            Name = "zapdos",
                            PokedexNumber = 145,
                            Type = "electric",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 146,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png",
                            Name = "moltres",
                            PokedexNumber = 146,
                            Type = "fire",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 147,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png",
                            Name = "dratini",
                            PokedexNumber = 147,
                            Type = "dragon",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 148,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png",
                            Name = "dragonair",
                            PokedexNumber = 148,
                            Type = "dragon",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 149,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png",
                            Name = "dragonite",
                            PokedexNumber = 149,
                            Type = "dragon",
                            Type2 = "flying"
                        },
                        new
                        {
                            Id = 150,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png",
                            Name = "mewtwo",
                            PokedexNumber = 150,
                            Type = "psychic",
                            Type2 = ""
                        },
                        new
                        {
                            Id = 151,
                            ImgUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png",
                            Name = "mew",
                            PokedexNumber = 151,
                            Type = "psychic",
                            Type2 = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
